src/Entity/Events.php
<?php

namespace App\Entity;

use App\Repository\EventsRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventsRepository::class)]
class Events
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(length: 2047)]
    private ?string $description = null;

    #[ORM\Column(length: 2047)]
    private ?string $image = null;

    #[ORM\Column]
    private ?int $capacity = null;

    #[ORM\Column(length: 255)]
    private ?string $contact_email = null;

    #[ORM\Column(length: 15)]
    private ?string $contact_phone = null;

    #[ORM\Column(length: 2047)]
    private ?string $location = null;

    #[ORM\Column(length: 2047, nullable: true)]
    private ?string $url = null;

    #[ORM\Column(length: 31, nullable: true)]
    private ?string $type = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(int $capacity): self
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getContactEmail(): ?string
    {
        return $this->contact_email;
    }

    public function setContactEmail(string $contact_email): self
    {
        $this->contact_email = $contact_email;

        return $this;
    }

    public function getContactPhone(): ?string
    {
        return $this->contact_phone;
    }

    public function setContactPhone(string $contact_phone): self
    {
        $this->contact_phone = $contact_phone;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(?string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;

        return $this;
    }
}

src/Form/EventsType.php
<?php

namespace App\Form;

use App\Entity\Events;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', null, array('attr' => ['class' => 'form-control']))
            ->add('date', null, array('attr' => ['class' => 'd-flex gap-3 form-control']))
            ->add('description', null, array('attr' => ['class' => 'form-control']))
            ->add('image', null, array('attr' => ['class' => 'form-control'])) 
            ->add('capacity', null, array('attr' => ['class' => 'form-control']))
            ->add('contact_email', null, array('attr' => ['class' => 'form-control']))
            ->add('contact_phone', null, array('attr' => ['class' => 'form-control']))
            ->add('location', null, array('attr' => ['class' => 'form-control']))
            ->add('url', null, array('attr' => ['class' => 'form-control']))
            ->add('type', null, array('attr' => ['class' => 'form-control']))
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Events::class,
        ]);
    }
}

src/Controller/EventsController.php
<?php

namespace App\Controller;

use App\Entity\Events;
use App\Form\EventsType;
use App\Repository\EventsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/events')]
class EventsController extends AbstractController
{
    #[Route('/', name: 'app_events_index', methods: ['GET'])]
    public function index(Request $request, EventsRepository $eventsRepository): Response
    {
        $eventType = $request->query->get('type');
        $events = [];

        if ($eventType) {
            $events = $eventsRepository->findBy(['type' => $eventType]);
        } else {
            $events = $eventsRepository->findAll();
        }

        return $this->render('events/index.html.twig', [
            'events' => $events,
        ]);
    }


    #[Route('/new', name: 'app_events_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EventsRepository $eventsRepository): Response
    {
        $event = new Events();
        $form = $this->createForm(EventsType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $eventsRepository->save($event, true);

            return $this->redirectToRoute('app_events_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('events/new.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_events_show', methods: ['GET'])]
    public function show(Events $event): Response
    {
        return $this->render('events/show.html.twig', [
            'event' => $event,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_events_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Events $event, EventsRepository $eventsRepository): Response
    {
        $form = $this->createForm(EventsType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $eventsRepository->save($event, true);

            return $this->redirectToRoute('app_events_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('events/edit.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_events_delete', methods: ['POST'])]
    public function delete(Request $request, Events $event, EventsRepository $eventsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $event->getId(), $request->request->get('_token'))) {
            $eventsRepository->remove($event, true);
        }

        return $this->redirectToRoute('app_events_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>
			{% block title %}Welcome!
			{% endblock %}
		</title>
		<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
		<link
		href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
		{# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
		{% block stylesheets %}{% endblock %}

		{% block javascripts %}{% endblock %}
		<style>
			.myCover {
				height: 100%;
				width: 100%;
				background-color: rgba(255, 255, 255, 0.5);
				box-shadow: 0 0 50px rgba(255, 255, 255, 1) inset;
			}
			.myCover:hover {
				background-color: rgba(255, 255, 255, 0.333);
				box-shadow: 0 0 50px rgba(255, 255, 255, 0.5) inset;
			}
			.myMin-height {
				min-height: 20rem;
			}
			@media(min-width: 1400px) {
				.col-c-4 {
					width: 33.333%;
				}
			}
		</style>
	</head>
	<body>

		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
			<div class="container">
				<a class="navbar-brand" href="/">EventManager</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						<li class="nav-item">
							<a class="nav-link active" aria-current="page" href="/">Events</a>
						</li>
						<li>
							<a class="nav-link" href="{{ path('app_events_new') }}">Create</a>
						</li>
						{# make the filter option exclusive #}
						{% if app.request.attributes.get('_route') in ['app_homepage', 'app_events_index'] or app.request.getRequestUri == '/' %}
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
								Filter
							</a>
							<ul class="dropdown-menu">
								<li>
									<a class="dropdown-item" href="{{ path('app_events_index', {'type': ''}) }}">All</a>
								</li>
								<li>
									<a class="dropdown-item" href="{{ path('app_events_index', {'type': 'music'}) }}">Music</a>
								</li>
								<li>
									<a class="dropdown-item" href="{{ path('app_events_index', {'type': 'sports'}) }}">Sports</a>
								</li>
								<li>
									<a class="dropdown-item" href="{{ path('app_events_index', {'type': 'poetry'}) }}">Poetry</a>
								</li>
								<li>
									<a class="dropdown-item" href="{{ path('app_events_index', {'type': 'art'}) }}">Art</a>
								</li>
								<li>
									<a class="dropdown-item" href="{{ path('app_events_index', {'type': 'expression'}) }}">Expression</a>
								</li>
							</ul>
						</li>
						{% endif %}
					</ul>
				</div>
			</div>
		</nav>

		<div class="container-fluid"> {% block body %}{% endblock %}
			</div>
			<footer class="bg-dark text-light text-center py-2 w-100 mt-3">
				<h6 class="display-5 fs-5">EventManager Rehovic 2023</h6>
			</footer>
			<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
		</body>
	</html>

templates/events/_delete_form.html.twig
<form method="post" action="{{ path('app_events_delete', {'id': event.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button class="btn btn-danger">delete</button>
</form>

templates/events/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>    
{{ form_end(form) }}

templates/events/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit
{% endblock %}

{% block body %}
	{{ form_start(form) }}
	{{ form_widget(form) }}
	<div class="d-flex mt-2 gap-2">
		<button class="btn btn-primary">{{ button_label|default('Update') }}</button>
		<a class="btn btn-dark" href="{{ path('app_events_index') }}">back to list</a>
		{{ include('events/_delete_form.html.twig') }}
	</div>
	{{ form_end(form) }}
{% endblock %}

templates/events/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home
{% endblock %}

{% block body %}
	<div class="row gx-2 gy-2 mt-2">
		{# loop through events and make custom "card" #}
		{% for event in events %}
			<div class="col-12 col-c-4 col-md-6">
				{# i know the id with a constant 0 at the start doesnt make a whole lot of sense but i think it looks cool! #}
				<h2 class="mx-5 fw-light text-light" style="position: absolute; font-size: 1rem;">[ID0{{ event.id }}]</h2>
				<a class="text-decoration-none" href="{{ path('app_events_show', {'id': event.id}) }}">
					{# twig / vsc is saying there's an error but i think its a false positive #}
					<div class="rounded-3 myMin-height" style="background-image: url( {{ event.image }} ); background-size: cover; background-position: center; background-repeat: no-repeat;">
						<div class="py-2 px-5 myCover myMin-height">
							<h2 class="display-2 text-dark fw-normal">{{ event.name }}</h2>
							<p class="bg-dark text-light w-50 px-2">{{ event.date ? event.date|date('Y/m/d H:i') : '' }}</p>
							{% if event.description|length > 40 %}
								<p class="bg-dark text-light w-50 px-2">{{ event.description|slice(0, 40) ~ '...' }}</p>
							{% else %}
								<p class="bg-dark text-light w-50 px-2">{{ event.description }}</p>
							{% endif %}
							<p class="bg-dark text-light w-50 px-2">our capacity: {{ event.capacity }}</p>
							<p class="bg-dark text-light w-50 px-2">{{ event.location }}</p>
						</div>
					</div>
				</a>
			</div>
		{% else %}
			<p>hmm, no events yet</p>
		{% endfor %}
	</div>	
{% endblock %}

templates/events/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create
{% endblock %}

{% block body %}
	{{ form_start(form) }}
	{{ form_widget(form) }}
	<div class="d-flex mt-2 gap-2">
		<button class="btn btn-primary">{{ button_label|default('Save') }}</button>
		<a class="btn btn-dark" href="{{ path('app_events_index') }}">back to list</a>
	</div>
	{{ form_end(form) }}
{% endblock %}

templates/events/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ event.name }}
{% endblock %}

{% block body %}
    {# idea here was sort of a hero, but on very large screens it looks kind of odd. #}
	<div class="rounded-3 mt-3" style="background-image: url( {{ event.image }} ); background-size: cover; background-position: center; background-repeat: no-repeat;">
        <div class="py-2 px-5 myCover myMin-height d-flex align-items-center" style="pointer-events: none">
            <h2 class="display-1 text-light fw-bold bg-dark p-2 px-4">{{ event.name }}</h2>
        </div>
    </div>
	
	<div class="accordion accordion-flush my-3" id="accordionFlushExample">
		<div class="accordion-item">
			<h2 class="accordion-header">
				<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
					Description
				</button>
			</h2>
			<div id="flush-collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
				<div class="accordion-body">
					<p>{{ event.description }}</p>
				</div>
			</div>
		</div>
		<div class="accordion-item">
			<h2 class="accordion-header">
				<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
					Details
				</button>
			</h2>
			<div id="flush-collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
				<div class="accordion-body">
					<table class="table">
						<tbody>
							<tr>
								<th>Id</th>
								<td>{{ event.id }}</td>
							</tr>
							<tr>
								<th>Date</th>
								<td>{{ event.date ? event.date|date('Y/m/d H:i') : '' }}</td>
							</tr>
							<tr>
								<th>Capacity</th>
								<td>{{ event.capacity }}</td>
							</tr>
							<tr>
								<th>Contact_email</th>
								<td>{{ event.contactEmail }}</td>
							</tr>
							<tr>
								<th>Contact_phone</th>
								<td>{{ event.contactPhone }}</td>
							</tr>
							<tr>
								<th>Location</th>
								<td>{{ event.location }}</td>
							</tr>
							<tr>
								<th>Url</th>
								<td>{{ event.url }}</td>
							</tr>
							<tr>
								<th>Type</th>
								<td>{{ event.type }}</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>

	<div class="d-flex">
		<a class="btn btn-dark" href="{{ path('app_events_index') }}">back to list</a>
		<a class="btn btn-outline-dark mx-2" href="{{ path('app_events_edit', {'id': event.id}) }}">edit</a>
		{{ include('events/_delete_form.html.twig') }}
	</div>

{% endblock %}